"""add sqlite autoincrement to urls

Revision ID: 1e450830b3af
Revises: 1b542b22a9ff
Create Date: 2026-07-29 23:52:10.787376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models.url import URL


# revision identifiers, used by Alembic.
revision: str = '1e450830b3af'
down_revision: Union[str, Sequence[str], None] = '1b542b22a9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("urls", copy_from=URL.__table__, recreate="always") as batch_op:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
